spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hatul?useSSL=false&default_authentication_plugin=mysql_native_password&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Jerusalem
    username: chserver
    password: vfnthy0tckjdJ
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
      check_nullability: true
  jwt.get.token.uri: /auth
  secret: $2y$04$mygZYT6qZ72/FSXpcvZ6tuzkJ1rF5Sd4rNtxJ13QT965CC24o6jYO
logging:
  file:
    name: log/hatulmadan.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger : %msg%n"
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hatulmadan.site.server: INFO

server:
  port: 8080

file:
  size: 5
  folder: attstorage
